# Generated by Django 4.2.7 on 2023-11-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header_detail', models.TextField()),
                ('line_item_detail', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=20)),
                ('approval_type', models.CharField(choices=[('small', 'small'), ('urgent', 'urgent'), ('adhoc', 'adhoc')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'client'), ('staff', 'staff'), ('admin', 'admin')], max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.company')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('threshold_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.user_profile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='approval.approval')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='approval',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_approvals', to='approval.user_profile'),
        ),
        migrations.AddField(
            model_name='approval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.workflow'),
        ),
    ]
