# Generated by Django 4.2.7 on 2023-11-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_user_profile_password_alter_approval_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('adhoc', 'adhoc'), ('urgent', 'urgent'), ('small', 'small')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.workflowstep'),
        ),
    ]
