# Generated by Django 4.2.7 on 2023-11-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_alter_approval_approval_type_alter_approval_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='workflow',
            new_name='workflowstep',
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('staff', 'staff'), ('admin', 'admin')], max_length=50),
        ),
    ]
