# Generated by Django 4.2.7 on 2023-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_rename_workflow_approval_workflowstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='sequence',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('urgent', 'urgent'), ('small', 'small'), ('adhoc', 'adhoc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('client', 'client'), ('admin', 'admin')], max_length=50),
        ),
    ]
