# Generated by Django 4.2.7 on 2023-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_approval_sequence_alter_approval_approval_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('small', 'small'), ('urgent', 'urgent'), ('adhoc', 'adhoc')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('approved', 'Approved'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='api_key',
            field=models.CharField(default=None, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('staff', 'staff'), ('admin', 'admin')], max_length=50),
        ),
    ]
