# Generated by Django 4.2.7 on 2023-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_alter_approval_approval_type_alter_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('urgent', 'urgent'), ('adhoc', 'adhoc'), ('small', 'small')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('client', 'client')], max_length=50),
        ),
    ]
