# Generated by Django 4.2.7 on 2023-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0010_workflowstep_users_alter_approval_approval_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='user',
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('urgent', 'urgent'), ('adhoc', 'adhoc'), ('small', 'small')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=20),
        ),
    ]
