# Generated by Django 4.2.7 on 2023-12-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0011_remove_workflowstep_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('adhoc', 'adhoc'), ('urgent', 'urgent'), ('small', 'small')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], max_length=20),
        ),
    ]
